spring:
  application:
    name: portal
  profiles:
    active: dev
  mail:
    host: smtp.qq.com
    username: 1641341031@qq.com
    password: yyflbioiopqucjgf

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: portal-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

secure:
  ignored:
    urls:
      - /druid/**
      - /actuator/**
      - /sso/**
      - /verify-code
      - /t-carousel/**
      - /pms-product-category/**
      - /pms-product/**
mybatis-plus:
  mapper-locations:
    - classpath*:*.xml