server:
  port: 8091

spring:
  datasource:
    # 192.168.1.101
    url: jdbc:mysql://45.32.127.9:3306/tigeryam_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    #root
    password: Hashmysql=1825
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet:
        login-username: druid
        login-password: druid

# OSS相关配置信息
aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI5t72EY1sNFAjcpWrZj6n # 访问身份验证中用到用户标识
    accessKeySecret: qJTMQ5BwhB3qZ4rspY1sFIWaMZsFya # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: tigeryam-oss # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://localhost:8091/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: tiger/images/ # 上传文件夹路径前缀
