spring:
  application:
    name: admin
  profiles:
    active: dev

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: portal-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

secure:
  ignored:
    urls:
      - /druid/**
      - /actuator/**
      - /admin/**
mybatis-plus:
  mapper-locations:
    - classpath*:*.xml